# Generated by Django 6.0.3 on 2026-06-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rainfall_level', models.CharField(max_length=50)),
                ('humidity_level', models.CharField(max_length=50)),
                ('temperature_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=100)),
                ('growth_duration_days', models.IntegerField()),
                ('sunlight_requirement', models.CharField(max_length=50)),
                ('water_requirement', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('fertilizer', models.TextField(blank=True)),
                ('planting', models.TextField(blank=True)),
                ('care_notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('best_season', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CropZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=20)),
                ('yield_expectation', models.CharField(max_length=50)),
                ('care_notes', models.TextField()),
                ('disease_risks', models.TextField(blank=True)),
                ('season', models.CharField(default='all', max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.climatezone')),
            ],
        ),
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('pest_risk_level', models.CharField(max_length=20)),
                ('main_threat', models.CharField(max_length=100)),
                ('prevention', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.climatezone')),
            ],
        ),
    ]
